-- Provider wallet ledger (credits for earned days, debits for withdrawals).
-- Referenced by payments wallet/payout routes and engagement-service completion.

CREATE TABLE IF NOT EXISTS public.provider_ledger
(
    ledger_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    serviceproviderid bigint NOT NULL,
    engagement_id bigint,
    amount numeric(12, 2) NOT NULL,
    direction character varying(10) COLLATE pg_catalog."default",
    reason character varying(50) COLLATE pg_catalog."default",
    reference_type character varying(50) COLLATE pg_catalog."default",
    reference_id bigint,
    created_at timestamp(6) without time zone DEFAULT now(),
    CONSTRAINT provider_ledger_pkey PRIMARY KEY (ledger_id)
);

CREATE INDEX IF NOT EXISTS idx_provider_ledger_serviceproviderid
    ON public.provider_ledger (serviceproviderid, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_provider_ledger_engagement_id
    ON public.provider_ledger (engagement_id)
    WHERE engagement_id IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'provider_ledger_serviceproviderid_fkey'
    ) THEN
        ALTER TABLE public.provider_ledger
            ADD CONSTRAINT provider_ledger_serviceproviderid_fkey
            FOREIGN KEY (serviceproviderid)
            REFERENCES public.serviceprovider (serviceproviderid)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;
    END IF;
EXCEPTION
    WHEN undefined_table THEN
        NULL;
END $$;
