-- On-demand promo: ₹99/hr on 1st lifetime booking and every 6th booking (6, 12, 18…).
-- discount_value = savings vs mid hourly rate (₹175 − ₹99 = ₹76) for a 1-hour quote at standard rate.
-- Pricing engine also applies ₹99/hr automatically via PROMO_HOURLY; these coupons surface the offer in the coupons API.

INSERT INTO public.coupons (
  coupon_id,
  coupon_code,
  description,
  service_type,
  discount_type,
  discount_value,
  minimum_order_value,
  usage_limit,
  usage_per_user,
  start_date,
  end_date,
  city,
  "isActive",
  booking_condition,
  nth_booking,
  created_at
)
VALUES
  (
    gen_random_uuid(),
    'MAID99-1ST',
    '₹99/hr on your 1st on-demand maid booking',
    'MAID',
    'FLAT',
    76,
    NULL,
    NULL,
    1,
    '2026-01-01 00:00:00',
    '2030-12-31 23:59:59',
    NULL,
    true,
    'FIRST_BOOKING',
    NULL,
    NOW()
  ),
  (
    gen_random_uuid(),
    'MAID99-6TH',
    '₹99/hr on your 6th on-demand maid booking',
    'MAID',
    'FLAT',
    76,
    NULL,
    NULL,
    1,
    '2026-01-01 00:00:00',
    '2030-12-31 23:59:59',
    NULL,
    true,
    'NTH_BOOKING',
    6,
    NOW()
  ),
  (
    gen_random_uuid(),
    'COOK99-1ST',
    '₹99/hr on your 1st on-demand cook booking',
    'COOK',
    'FLAT',
    76,
    NULL,
    NULL,
    1,
    '2026-01-01 00:00:00',
    '2030-12-31 23:59:59',
    NULL,
    true,
    'FIRST_BOOKING',
    NULL,
    NOW()
  ),
  (
    gen_random_uuid(),
    'COOK99-6TH',
    '₹99/hr on your 6th on-demand cook booking',
    'COOK',
    'FLAT',
    76,
    NULL,
    NULL,
    1,
    '2026-01-01 00:00:00',
    '2030-12-31 23:59:59',
    NULL,
    true,
    'NTH_BOOKING',
    6,
    NOW()
  )
ON CONFLICT (coupon_code) DO UPDATE SET
  description = EXCLUDED.description,
  service_type = EXCLUDED.service_type,
  discount_type = EXCLUDED.discount_type,
  discount_value = EXCLUDED.discount_value,
  usage_per_user = EXCLUDED.usage_per_user,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  "isActive" = true,
  booking_condition = EXCLUDED.booking_condition,
  nth_booking = EXCLUDED.nth_booking;
